### ISSUE TITLE
rospy_azure_iothub Demo on Windows 10 using Visual Studio Code

### ISSUE THREAD

**Issue by jsimard-cegeptr** [Microsoft/ros_azure_iothub#14]
Hi,

I'm trying to make rospy_azure_iothub works using Visual Studio Code. Not able to launch, since not able to find rosbridge_library.

```
Traceback (most recent call last):
  File "D:\CATKIN_WORKSPACE\src\rospy_azure_iothub\ros_azure_iothub", line 63, in <module>
    from rosbridge_library.internal import message_conversion
ImportError: No module named rosbridge_library.internal 
```

Also tryied rosdep (rosdep install --from-paths src --ignore-src --rosdistro melodic -r -y), but without success too : 

`ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rospy_azure_iothub: No definition of [rosbridge_library] for OS [windows]`

I have installed both azure-iot-device and azure-iot-hub.

Is it supposed to work?

Thanks!

**Comment by seanyen** [comment]
@jsimard-cegeptr Thanks for reporting this issue. In general, you will need to add `rosbridge_library` sources into your workspace and build again. I see there is some room for doc improvement. Let me update the docs side and get back to you.

**Comment by jsimard-cegeptr** [comment]
Thanks for the quick reply, really appreciated! And it works!
