### ISSUE TITLE
linux build fails

### ISSUE THREAD

**Issue by tervoju** [Microsoft/ros_azure_iothub#20]
catkin_make install 

with this error

-- Could NOT find ros_type_introspection (missing: ros_type_introspection_DIR)
-- Could not find the required component 'ros_type_introspection'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "ros_type_introspection" with any of the following names:

    ros_type_introspectionConfig.cmake
    ros_type_introspection-config.cmake

after adding this foloowing error:

CMake Error at ros_azure_iothub/roscpp_azure_iothub/CMakeLists.txt:25 (find_package):
  Could not find a package configuration file provided by "azure_iot_sdks"
  with any of the following names:

    azure_iot_sdksConfig.cmake
    azure_iot_sdks-config.cmake

  Add the installation prefix of "azure_iot_sdks" to CMAKE_PREFIX_PATH or set
  "azure_iot_sdks_DIR" to a directory containing one of the above files.  If
  "azure_iot_sdks" provides a separate development package or SDK, be sure it

**Comment by ooeygui** [comment]
Hi @tervoju,
I'd love to understand more about your scenario, would you be willing to chat with us about it?

Both of these dependencies should be resolved using the rosdep command listed in the instructions at `https://github.com/microsoft/ros_azure_iothub/tree/melodic-devel/roscpp_azure_iothub`.

Can you paste the output of the rosdep command?

**Comment by tervoju** [comment]
**rosdep update**
--->
jte@jte-Virtual-Machine:~/ros_ws/ros_azure$ sudo rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Warning: running 'rosdep update' as root is not recommended.
  You should run 'sudo rosdep fix-permissions' and invoke 'rosdep update' again without sudo.
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Add distro "dashing"
Add distro "eloquent"
Add distro "foxy"
Skip end-of-life distro "groovy"
Skip end-of-life distro "hydro"
Skip end-of-life distro "indigo"
Skip end-of-life distro "jade"
Add distro "kinetic"
Skip end-of-life distro "lunar"
Add distro "melodic"
Add distro "noetic"
updated cache in /home/jte/.ros/rosdep/sources.cache

**rosdep install**
-->
jte@jte-Virtual-Machine:~/ros_ws/ros_azure$ sudo rosdep install --from-paths src --ignore-src -r -y
WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 2
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies (ROS distro is not set. Make sure `ROS_DISTRO` environment variable is set, or use `--rosdistro` option to specify the distro, e.g. `--rosdistro indigo`):
ros_type_introspection: Cannot locate rosdep definition for [rostime]
rospy_azure_iothub: Cannot locate rosdep definition for [rosbridge_library]
roscpp_azure_iothub: Cannot locate rosdep definition for [rosunit]
dynamic_tutorials: Cannot locate rosdep definition for [roscpp]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully

**Comment by tervoju** [comment]
and with --rosdistro melodic flag

jte@jte-Virtual-Machine:~/ros_ws/ros_azure$ sudo rosdep install --from-paths src --ignore-src -r -y --rosdistro melodic 
[sudo] password for jte: 
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rospy_azure_iothub: Cannot locate rosdep definition for [python-azure-iothub-device-client]
roscpp_azure_iothub: Cannot locate rosdep definition for [libazure-iot-sdk-c]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully

**Comment by tervoju** [comment]
@ooeygui  do you need more info?

**Comment by ooeygui** [comment]
@tervoju Thanks for the ping, We are almost done with the fix. should be in PR today.
