### ISSUE TITLE
Install failing with ROS Melodic because of missing parson

### ISSUE THREAD

**Issue by shmpwk** [Microsoft/ros_azure_iothub#43]
This issue happens after #41 is  solved.

I'm trying the [How to Build (Ubuntu Linux Melodic install)](https://github.com/microsoft/ros_azure_iothub/tree/melodic-devel/roscpp_azure_iothub#how-to-build-ubuntu-linux-melodic-install).

My environment is ubuntu18.04 on WSL2 and ROS Melodic.

When executing `catkin_make install`, the error say cannot find parson.

**Comment by shmpwk** [comment]
I checkout melodic-devel branch but nothing is found under the ros_azure_iothub/roscpp_azure_iothub/parson directory.

So we should specify melodic-devel branch when cloning the repo.

In the end, I solve the problem by executing 
```
git clone -b melodic-devel --recursive https://github.com/Microsoft/ros_azure_iothub
```
instead of
```
git clone --recursive https://github.com/Microsoft/ros_azure_iothub
```

**Comment by yahanda** [comment]
+1 experiencing the same issue with Ubuntu 18.04 + ROS Melodic. Thanks @shmpwk for the workaround.
